version: '3.8'
services:
  gateway:
    build:
      context: .
      target: gateway
    image: registry.nicedoc.cn/biyue-gateway:${PRODUCT_VERSION}

  auth:
    build:
      context: .
      target: auth
    image: registry.nicedoc.cn/biyue-auth:${PRODUCT_VERSION}

  callback:
    build:
      context: .
      target: callback
    image: registry.nicedoc.cn/biyue-callback:${PRODUCT_VERSION}
