version: '3.8'
services:
  onlyoffice-documentserver:
    image: registry.nicedoc.cn/nicedoc-documentserver   
    container_name: onlyoffice-documentserver
    depends_on:
      - onlyoffice-postgresql
      - onlyoffice-rabbitmq
    environment:
      - DB_TYPE=postgres
      - DB_HOST=onlyoffice-postgresql
      - DB_PORT=5432
      - DB_NAME=onlyoffice
      - DB_USER=onlyoffice
      - AMQP_URI=amqp://guest:guest@onlyoffice-rabbitmq
      # Uncomment strings below to enable the JSON Web Token validation.
      - JWT_ENABLED=true
      - JWT_SECRET=nZPjI3XNp818tl7H8ovVTgmjOz9RuWts
      - JWT_HEADER=Authorization
      - JWT_IN_BODY=false
    ports:
      - '80:80'
      - '443:443'
    stdin_open: true
    restart: always
    stop_grace_period: 60s
    volumes:
       - /var/www/onlyoffice/Data
       - /var/log/onlyoffice
       - /var/lib/onlyoffice/documentserver/App_Data/cache/files
       - /var/www/onlyoffice/documentserver-example/public/files
       - /usr/share/fonts
       - ~/oo:/onlyoffice
    networks:
      default: 
        aliases:
          - start.localtest.me  

  onlyoffice-rabbitmq:
    container_name: onlyoffice-rabbitmq
    image: rabbitmq
    restart: always
    expose:
      - '5672'

  onlyoffice-postgresql:
    container_name: onlyoffice-postgresql
    image: postgres:12
    environment:
      - POSTGRES_DB=onlyoffice
      - POSTGRES_USER=onlyoffice
      - POSTGRES_HOST_AUTH_METHOD=trust
    restart: always
    expose:
      - '5432'
    volumes:
      - postgresql_data:/var/lib/postgresql
  
  onlyoffice-biyueplugin:
    container_name: onlyoffice-biyueplugin
    image: registry.nicedoc.cn/biyue-plugin
    restart: always
    volumes:
      - plugin_data:/var/www/onlyoffice/documentserver/sdkjs-plugins/biyue

  gateway:    
    image: registry.nicedoc.cn/biyue-gateway
    volumes:
      - ./services/gateway/config:/usr/src/app/config
    environment:
      - SERVER_NAMESPACE=biyue
      - SERVER_NAME=gateway
      - SERVER_ADDRESS=:4044
      - REPL_ADDRESS=:9999
      - SERVER_DEBUG=true
      - STORAGE_TYPE=0
      - STORAGE_URL=mongodb://root:example@mongo:27017/
      - STORAGE_DB=biyue
      - TRACER_NAME=gateway
      - TRACER_ENABLE=true
      - TRACER_ADDRESS=http://jaeger.localtest.me:9411
      - TRACER_TYPE=1
      - LOGGER_NAME=gateway-logger
      - LOGGER_LEVEL=1
      - LOGGER_COLOR=true
      - REGISTRY_ADDRESSES=consul
      - REGISTRY_TYPE=2
      # biyue host
      - BIYUE_API_ENDPOINT=https://eduques.xmdas-link.com/bonlyoffice/oodoc      
      - BIYUE_API_TEST_TOKEN=56f47fafdaec3584e184fbfd3f6f11d5
      - BIYUE_AUTH_ENDPOINT=https://eduteacher.xmdas-link.com/question/

      # credentials
      - CREDENTIALS_CLIENT_ID=biyue
      - CREDENTIALS_CLIENT_SECRET=DswSou7kQkhfP4qep3q6s4uE55jXdqzl
      - CREDENTIALS_REDIRECT_URL=http://gateway.localtest.me:4044/oauth/redirect      
      - CREDENTIALS_SCOPES=openid profile email phone address
      - CREDENTIALS_AUTH_URL=https://eduteacher.xmdas-link.com/
      - CREDENTIALS_TOKEN_URL=http://keycloak.localtest.me:8080/realms/biyue/protocol/openid-connect/token
      
      # Onlyoffice
      - ONLYOFFICE_DS_URL=http://start.localtest.me
      - ONLYOFFICE_DS_SECRET=nZPjI3XNp818tl7H8ovVTgmjOz9RuWts
      - ONLYOFFICE_DS_HEADER=Authorization
      - ONLYOFFICE_GATEWAY_URL=http://gateway.localtest.me:4044
      - ONLYOFFICE_CALLBACK_URL=http://callback.localtest.me:5044
      - ONLYOFFICE_ALLOWED_DOWNLOADS=1
      - ONLYOFFICE_CALLBACK_MAX_SIZE=210000000000
      - ONLYOFFICE_CALLBACK_UPLOAD_TIMEOUT=120
    # cors
      - ALLOWED_ORIGINS=*
      - ALLOWED_METHODS=GET,POST,DELETE,OPTIONS,PUT
      - ALLOWED_HEADERS=*, X-Token, X-User, xtoken
    ports:
          - 4044:4044    
    networks:
      default: 
        aliases:
          - gateway.localtest.me  

  auth:    
    image: registry.nicedoc.cn/biyue-auth
    environment:
      - SERVER_NAMESPACE=biyue
      - SERVER_NAME=auth
      - SERVER_ADDRESS=:5052
      - REPL_ADDRESS=:5053
      - SERVER_DEBUG=true
      - STORAGE_TYPE=0
      - STORAGE_URL=mongodb://root:example@mongo:27017/
      - STORAGE_DB=biyue
      - TRACER_NAME=auth
      - TRACER_ENABLE=true
      - TRACER_ADDRESS=http://jaeger.localtest.me:9411
      - TRACER_TYPE=1
      - LOGGER_NAME=auth-logger
      - LOGGER_LEVEL=1
      - LOGGER_COLOR=true
      - REGISTRY_ADDRESSES=consul
      - REGISTRY_TYPE=2

  callback:
    image: registry.nicedoc.cn/biyue-callback
    environment:
      # ServerConfig
      - SERVER_NAMESPACE=biyue
      - SERVER_NAME=callback        
      - SERVER_ADDRESS=:5044
      - SERVER_DEBUG=true
      - REPL_ADDRESS=:3132
      # RegistryConfig
      - REGISTRY_ADDRESSES=consul
      - REGISTRY_TYPE=2
      # StorageConfig
      - STORAGE_TYPE=0
      - STORAGE_URL=mongodb://root:example@mongo:27017/
      - STORAGE_DB=biyue
      # TracerConfig
      - TRACER_NAME=callback
      - TRACER_ENABLE=true
      - TRACER_ADDRESS=http://jaeger.localtest.me:9411
      - TRACER_TYPE=1
      # LoggerConfig
      - LOGGER_NAME=callback-logger      
      - LOGGER_LEVEL=1
      - LOGGER_COLOR=true
      # Onlyoffice
      - ONLYOFFICE_DS_URL=http://start.localtest.me
      - ONLYOFFICE_DS_SECRET=nZPjI3XNp818tl7H8ovVTgmjOz9RuWts
      - ONLYOFFICE_DS_HEADER=Authorization
      - ONLYOFFICE_GATEWAY_URL=http://gateway.localtest.me:4044
      - ONLYOFFICE_CALLBACK_URL=http://callback.localtest.me:5044
      - ONLYOFFICE_ALLOWED_DOWNLOADS=1
      - ONLYOFFICE_CALLBACK_MAX_SIZE=210000000000
      - ONLYOFFICE_CALLBACK_UPLOAD_TIMEOUT=120
      # Biyue
      - BIYUE_API_ENDPOINT=https://eduques.xmdas-link.com/bonlyoffice/oodoc      
      - BIYUE_API_TEST_TOKEN=56f47fafdaec3584e184fbfd3f6f11d5
    networks:
      default: 
        aliases:
          - callback.localtest.me     
 
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/    
  
  jaeger:
    image: jaegertracing/all-in-one:1.56
    ports:
      - 16686:16686
      - 4317:4317
      - 4318:4318
      - 9411:9411
    environment:
      - LOGGER_LEVEL=DEBUG      
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
    networks:
      default:
        aliases:
          - jaeger.localtest.me

  consul:
    image: consul:1.15.4
    container_name: consul
    ports:
      - "8500:8500"  # Consul Web UI 端口
      - "8600:8600/udp"  # Consul DNS 查询端口


volumes:
  postgresql_data:
  plugin_data:

