version: '3.8'
services:
  gateway:
    build:
      context: ../
      target: gateway
    image: registry.nicedoc.cn/biyue-gateway:${PRODUCT_VERSION}
    volumes:
      - ./services/gateway/config:/usr/src/app/config
    environment:
      - SERVER_NAMESPACE=biyue
      - SERVER_NAME=gateway
      - SERVER_ADDRESS=:4044
      - REPL_ADDRESS=:9999
      - SERVER_DEBUG=true
      - STORAGE_TYPE=0
      - STORAGE_URL=mongodb://root:example@mongo:27017/
      - STORAGE_DB=biyue
      - TRACER_NAME=gateway
      - TRACER_ENABLE=true
      - TRACER_ADDRESS=http://jaeger.localtest.me:9411
      - TRACER_TYPE=1
      - LOGGER_NAME=gateway-logger
      - LOGGER_LEVEL=1
      - LOGGER_COLOR=true
      - REGISTRY_ADDRESSES=consul
      - REGISTRY_TYPE=2
      # credentials
      - CREDENTIALS_CLIENT_ID=biyue
      - CREDENTIALS_CLIENT_SECRET=MaaS1q6oSm351t5TL0v6Pt64laTmTwfg
      - CREDENTIALS_REDIRECT_URL=http://gateway.localtest.me:4044/oauth/redirect
      - CREDENTIALS_SCOPES=openid profile email phone address
      - CREDENTIALS_AUTH_URL=http://keycloak.localtest.me:8080/realms/biyue/protocol/openid-connect/auth
      - CREDENTIALS_TOKEN_URL=http://keycloak.localtest.me:8080/realms/biyue/protocol/openid-connect/token
      # S3 minio
      #{"url":"http://minio.localtest.me:9090"
      #"accessKey":"sX0pF2T9FwYr5TQ9G2xg",
      # "secretKey":"NQg1DuGQivBigVhb2drxRUwx6M20eFgIUlh3r01H","api":"s3v4","path":"auto"}
      - S3_URL=minio.localtest.me:9000
      - S3_BUCKET=test
      - S3_ACCESS_KEY=sX0pF2T9FwYr5TQ9G2xg
      - S3_SECRET_KEY=NQg1DuGQivBigVhb2drxRUwx6M20eFgIUlh3r01H
      - S3_API=s3v4
      - S3_PATH=auto  
      # Onlyoffice
      - ONLYOFFICE_DS_URL=http://localhost
      - ONLYOFFICE_DS_SECRET=nZPjI3XNp818tl7H8ovVTgmjOz9RuWts
      - ONLYOFFICE_DS_HEADER= Authorization
      - ONLYOFFICE_GATEWAY_URL=http://gateway.localtest.me:4044
      - ONLYOFFICE_CALLBACK_URL=http://callback.localtest.me:5044
      - ONLYOFFICE_ALLOWED_DOWNLOADS=1
      - ONLYOFFICE_CALLBACK_MAX_SIZE=210000000000
      - ONLYOFFICE_CALLBACK_UPLOAD_TIMEOUT=120

    ports:
          - 4044:4044    
    networks:
      keycloak: 
        aliases:
          - gateway.localtest.me  

  auth:
    build:
      context: ../
      target: auth
    image: registry.nicedoc.cn/biyue-auth:${PRODUCT_VERSION}
    environment:
      - SERVER_NAMESPACE=biyue
      - SERVER_NAME=auth
      - SERVER_ADDRESS=:5052
      - REPL_ADDRESS=:5053
      - SERVER_DEBUG=true
      - STORAGE_TYPE=0
      - STORAGE_URL=mongodb://root:example@mongo:27017/
      - STORAGE_DB=biyue
      - TRACER_NAME=auth
      - TRACER_ENABLE=true
      - TRACER_ADDRESS=http://jaeger.localtest.me:9411
      - TRACER_TYPE=1
      - LOGGER_NAME=auth-logger
      - LOGGER_LEVEL=1
      - LOGGER_COLOR=true
      - REGISTRY_ADDRESSES=consul
      - REGISTRY_TYPE=2
    networks:
      keycloak: {}      

  callback:
    build:
      context: ../
      target: callback
    image: registry.nicedoc.cn/biyue-callback:${PRODUCT_VERSION}
    environment:
      # ServerConfig
      - SERVER_NAMESPACE=biyue
      - SERVER_NAME=callback        
      - SERVER_ADDRESS=:5044
      - SERVER_DEBUG=true
      - REPL_ADDRESS=:3132
      # RegistryConfig
      - REGISTRY_ADDRESSES=consul
      - REGISTRY_TYPE=2
      # StorageConfig
      - STORAGE_TYPE=0
      - STORAGE_URL=mongodb://root:example@mongo:27017/
      - STORAGE_DB=biyue
      # TracerConfig
      - TRACER_NAME=callback
      - TRACER_ENABLE=true
      - TRACER_ADDRESS=http://jaeger.localtest.me:9411
      - TRACER_TYPE=1
      # LoggerConfig
      - LOGGER_NAME=callback-logger      
      - LOGGER_LEVEL=1
      - LOGGER_COLOR=true
      # S3
      - S3_URL=minio.localtest.me:9000
      - S3_BUCKET=test
      - S3_ACCESS_KEY=sX0pF2T9FwYr5TQ9G2xg
      - S3_SECRET_KEY=NQg1DuGQivBigVhb2drxRUwx6M20eFgIUlh3r01H
      - S3_API=s3v4
      - S3_PATH=auto  
      # Onlyoffice
      - ONLYOFFICE_DS_URL=http://localhost
      - ONLYOFFICE_DS_SECRET=nZPjI3XNp818tl7H8ovVTgmjOz9RuWts
      - ONLYOFFICE_DS_HEADER= Authorization
      - ONLYOFFICE_GATEWAY_URL=http://gateway.localtest.me:4044
      - ONLYOFFICE_CALLBACK_URL=http://callback.localtest.me:5044
      - ONLYOFFICE_ALLOWED_DOWNLOADS=1
      - ONLYOFFICE_CALLBACK_MAX_SIZE=210000000000
      - ONLYOFFICE_CALLBACK_UPLOAD_TIMEOUT=120
    networks:
      keycloak: 
        aliases:
          - callback.localtest.me
     
 
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      keycloak: {}      

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
    networks:
      keycloak: {}      
  
  jaeger:
    image: jaegertracing/all-in-one:1.56
    ports:
      - 16686:16686
      - 4317:4317
      - 4318:4318
      - 9411:9411
    environment:
      - LOGGER_LEVEL=DEBUG      
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
    networks:
      keycloak:
        aliases:
          - jaeger.localtest.me

  consul:
    image: consul:1.15.4
    container_name: consul
    ports:
      - "8500:8500"  # Consul Web UI 端口
      - "8600:8600/udp"  # Consul DNS 查询端口
    networks:
      keycloak: {}

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9090:9090"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    volumes:
      - minio:/data/minio
      - ./minio/config:/root/.minio
    command: minio server /data/minio --console-address ":9090"
    # Access Key: 5PAF2NO0EGGCwLAF479g
    # Secret Key: 83TOXebft3hCUg9nQyz36HKpmnbYNifkBo6GCYby
    networks:
      keycloak:
        aliases:
          - minio.localtest.me


  keycloak:
    image: quay.io/keycloak/keycloak
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - "8080:8080"      
    command: "start-dev" 
    volumes:
       - ./keycloak:/opt/keycloak/data/import
    networks:
      keycloak:
        aliases:
          - keycloak.localtest.me

  oauth2-proxy:
    container_name: oauth2-proxy
    image: quay.io/oauth2-proxy/oauth2-proxy:v7.6.0
    command: --config /oauth2-proxy.cfg
    hostname: oauth2-proxy
    volumes:
      - ./oauth2-proxy-keycloak.cfg:/oauth2-proxy.cfg
    ports:
      - 4180:4180/tcp
    networks:
      keycloak:
        aliases:
          - oauth2-proxy.localtest.me
    depends_on:
      - keycloak
      - nginx

  nginx:
    container_name: nginx
    image: nginx:latest
    hostname: start
    volumes:
      - ./test:/usr/share/nginx/html
    ports:
      - 9080:80
    networks:
      keycloak: 
        aliases:
          - start.localtest.me

networks:
  keycloak: {}
  oauth2-proxy: {}


volumes:
  minio:
    driver: local