namespace: "biyue"
name: "auth"
version: 0
address: ":5052"
repl_address: ":5053"
debug: true
storage:
  type: 1
  url: "mongodb://root:example@mongo:27017/" 
pesistence:
  type: 1
  url: "mongodb://root:example@mongo:27017/"
  database: "auth"
  collection: "auth"
registry:
  addresses: [""]
  type: 2
tracer:
  enable: false
  address: "grpc://otel-collector:4317"
  type: 1
resilience:
  rate_limiter:
    limit: 500
  circuit_breaker:
    timeout: 2500
logger:
  name: "auth-logger"
  level: 1
  color: true
oauth:
  project_id: ""
  client_id: ""
  client_secret: ""
  auth_uri: ""
  token_uri: ""
  auth_provider_x509_cert_url: ""
  redirect_uris: [""]
  javascript_origins: [""]