name: Build biyue connector

run-name: >
     Build biyue version: ${{ github.event.inputs.version }}

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Set version that will be used for images tag'
        type: string
        required: true

env: 
  PRODUCT_VERSION: ${{ github.event.inputs.version }}
          
jobs:
  build:
    name: "Build tag: ${{ github.event.inputs.version }}"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to NiceDoc.cn Registry
        uses: docker/login-action@v2
        with:
          registry: registry.nicedoc.cn
          username: ${{ secrets.NICEDOC_REGISTRY_USER }}
          password: ${{ secrets.NICEDOC_REGISTRY_PASS }}

      - name: Build connector
        shell: bash
        run: |
          docker compose build 
          docker compose push
          docker images